'use client';

import { useEffect, useCallback } from 'react';
import { Header } from '@/components/header';
import { SearchBox } from '@/components/search-box';
import { CommandCard } from '@/components/command-card';
import { EmptyState } from '@/components/empty-state';
import { LoadingSkeleton } from '@/components/loading-skeleton';
import { ErrorState } from '@/components/error-state';
import { NoResults } from '@/components/no-results';
import { useSearch } from '@/hooks/use-search';

export default function Home() {
  const { query, setQuery, data, loading, error, selectedIndex, setSelectedIndex } =
    useSearch();

  const handleKeyDown = useCallback(
    (e: KeyboardEvent) => {
      if (!data || data.results.length === 0) return;

      if (e.key === 'ArrowDown') {
        e.preventDefault();
        setSelectedIndex(Math.min(selectedIndex + 1, data.results.length - 1));
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setSelectedIndex(Math.max(selectedIndex - 1, 0));
      } else if (e.key === 'Enter' && selectedIndex >= 0) {
        const result = data.results[selectedIndex];
        if (result) {
          navigator.clipboard.writeText(result.entry.command).catch(() => {});
        }
      }
    },
    [data, selectedIndex, setSelectedIndex],
  );

  useEffect(() => {
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  const hasQuery = query.trim().length > 0;
  const showEmpty = !hasQuery && !loading && !error;
  const showNoResults =
    hasQuery && !loading && !error && data && data.results.length === 0;
  const showResults =
    hasQuery && !loading && !error && data && data.results.length > 0;

  return (
    <div className="min-h-screen bg-background">
      {/* Background gradient */}
      <div className="pointer-events-none fixed inset-0 overflow-hidden">
        <div className="absolute -top-40 left-1/2 -translate-x-1/2 h-96 w-[600px] rounded-full bg-primary/5 blur-3xl" />
        <div className="absolute top-1/3 -right-40 h-64 w-64 rounded-full bg-violet-500/5 blur-3xl" />
        <div className="absolute bottom-0 -left-40 h-64 w-64 rounded-full bg-emerald-500/5 blur-3xl" />
      </div>

      <Header />

      <main className="relative mx-auto max-w-3xl px-4 py-8">
        {/* Hero */}
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Find the right <span className="text-gradient">terminal command</span>
          </h1>
          <p className="mt-2 text-sm text-muted-foreground sm:text-base">
            Describe what you want in plain English. Get the exact command instantly.
          </p>
        </div>

        {/* Search */}
        <div className="mb-6">
          <SearchBox value={query} onChange={setQuery} loading={loading} />
        </div>

        {/* Content */}
        <div className="space-y-3">
          {showEmpty && <EmptyState onSuggestionClick={setQuery} />}
          {loading && <LoadingSkeleton />}
          {error && <ErrorState message={error} />}
          {showNoResults && <NoResults />}
          {showResults && (
            <>
              {data?.llmUsed && (
                <div className="flex items-center gap-2 rounded-lg border border-violet-500/20 bg-violet-500/5 px-3 py-2 text-xs text-violet-600 dark:text-violet-400">
                  <span className="font-semibold">AI Fallback:</span>
                  <span>
                    No confident match in the dataset. This command was generated by an LLM.
                  </span>
                </div>
              )}
              {data?.results.map((result, i) => (
                <CommandCard
                  key={result.entry.id}
                  result={result}
                  index={i}
                  isSelected={i === selectedIndex}
                  onSelect={() => setSelectedIndex(i)}
                />
              ))}
              {data && (
                <p className="pt-2 text-center text-xs text-muted-foreground/50">
                  {data.results.length} result{data.results.length !== 1 ? 's' : ''} ·
                  {' '}{data.latencyMs}ms ·
                  {' '}{data.llmUsed ? 'AI fallback' : 'Semantic retrieval'}
                  {' '}· Press ↑↓ to navigate, Enter to copy
                </p>
              )}
            </>
          )}
        </div>
      </main>

      <footer className="relative mx-auto max-w-3xl px-4 py-8 text-center text-xs text-muted-foreground/50">
        <p>
          CmdFind — Semantic search over {200}+ Linux commands with AI fallback.
          Built with Next.js, FAISS & sentence-transformers.
        </p>
      </footer>
    </div>
  );
}
