import type { CommandEntry, LLMGeneratedCommand, SafetyLevel } from './types';

const OLLAMA_URL = process.env.OLLAMA_URL || 'http://localhost:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'llama3.2';
const PYTHON_BACKEND_URL = process.env.PYTHON_BACKEND_URL || 'http://localhost:8000';

interface PythonBackendResponse {
  command: string;
  explanation: string;
  flags: { flag: string; description: string }[];
  example: string;
  safety: SafetyLevel;
  source: string;
}

async function tryPythonBackend(query: string, signal?: AbortSignal): Promise<LLMGeneratedCommand | null> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(`${PYTHON_BACKEND_URL}/llm/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query }),
      signal: signal ?? controller.signal,
    });
    clearTimeout(timeout);
    if (!res.ok) return null;
    const data: PythonBackendResponse = await res.json();
    return {
      command: data.command,
      explanation: data.explanation,
      flags: data.flags,
      example: data.example,
      safety: data.safety,
    };
  } catch {
    return null;
  }
}

function buildPrompt(query: string): string {
  return `You are a Linux terminal command expert. The user wants a terminal command for the following request:

"${query}"

Respond ONLY with a valid JSON object (no markdown, no code fences) with these fields:
- "command": the exact terminal command
- "explanation": a clear one-sentence explanation of what it does
- "flags": an array of objects with "flag" and "description" for each flag used
- "example": a concrete example of using the command
- "safety": one of "safe", "warning", or "dangerous"

Example response:
{"command":"find . -type d -empty -delete","explanation":"Finds and removes all empty directories recursively.","flags":[{"flag":"-type d","description":"Match directories only"},{"flag":"-empty","description":"Match empty entries"},{"flag":"-delete","description":"Delete matched entries"}],"example":"find . -type d -empty -delete","safety":"warning"}`;
}

function extractJson(text: string): LLMGeneratedCommand | null {
  let cleaned = text.trim();
  cleaned = cleaned.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '');

  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  if (!jsonMatch) return null;

  try {
    const parsed = JSON.parse(jsonMatch[0]);
    if (!parsed.command || typeof parsed.command !== 'string') return null;
    return {
      command: parsed.command,
      explanation: parsed.explanation || 'Generated by AI fallback.',
      flags: Array.isArray(parsed.flags) ? parsed.flags : [],
      example: parsed.example || parsed.command,
      safety: (['safe', 'warning', 'dangerous'].includes(parsed.safety) ? parsed.safety : 'warning') as SafetyLevel,
    };
  } catch {
    return null;
  }
}

async function tryOllama(query: string, signal?: AbortSignal): Promise<LLMGeneratedCommand | null> {
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 30000);
    const res = await fetch(`${OLLAMA_URL}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        prompt: buildPrompt(query),
        stream: false,
        options: { temperature: 0.3, top_p: 0.9 },
      }),
      signal: signal ?? controller.signal,
    });
    clearTimeout(timeout);
    if (!res.ok) return null;
    const data = await res.json();
    return extractJson(data.response || '');
  } catch {
    return null;
  }
}

export async function generateWithLLM(
  query: string,
  signal?: AbortSignal,
): Promise<LLMGeneratedCommand | null> {
  const pythonResult = await tryPythonBackend(query, signal);
  if (pythonResult) return pythonResult;

  const ollamaResult = await tryOllama(query, signal);
  if (ollamaResult) return ollamaResult;

  return null;
}

export function llmResultToEntry(
  query: string,
  generated: LLMGeneratedCommand,
): CommandEntry {
  return {
    id: `llm-${Date.now()}`,
    command: generated.command,
    description: `AI-generated for: "${query}"`,
    category: 'AI Generated',
    tags: ['ai-generated', 'fallback'],
    example: generated.example,
    safety: generated.safety,
    explanation: generated.explanation,
    flags: generated.flags,
  };
}
